apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
  labels:
    app: redis
    project: roboshop
    tier: db
spec:
  ports:
  - protocol: TCP
    port: 3306 #service-port
    targetPort: 3306
  clusterIP: None
  selector:
    app: redis
    project: roboshop
    tier: db